name: commcare-export release actions
on:
  release:
    types: [published]

jobs:
  generate_linux_bin:
    name: Generate Linux binary as release asset
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # setuptools-scm needs full git history

      - uses: astral-sh/setup-uv@v4

      - shell: bash
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install pyinstaller
          uv pip install "commcare-export[executable]"

      - shell: bash
        run: |
          source .venv/bin/activate
          pyinstaller --dist ./dist/linux commcare-export.spec

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "./dist/linux/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  generate_windows_exe:
    name: Generate Windows exe as release asset
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # setuptools-scm needs full git history

      - uses: astral-sh/setup-uv@v4

      - shell: pwsh
        run: |
          uv venv
          .venv\Scripts\Activate.ps1
          uv pip install pyinstaller
          uv pip install "commcare-export[executable]"

      - shell: pwsh
        run: |
          .venv\Scripts\Activate.ps1
          pyinstaller --dist ./dist/windows commcare-export.spec

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "./dist/windows/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
